### ISSUE TITLE
please apply user fix to feelpp/feelpp-toolboxes:develop-ubuntu-16.10 

### ISSUE THREAD

**Issue by Trophime** [feelpp/docker#9]
``` docker run -it -e LOCAL_USER_ID=`id -u $USER` myimage``` and ```docker run -it -e LOCAL_USER_ID=`id -u $USER` myimage``` gives the same user id!!!

**Comment by prudhomm** [comment]
what is the problem ?

the id is that the user in docker is the same as the one mounting `FEELPP_DIR` so that we have write access. if you don't provide `LOCAL_USER_ID` then it reverts to a default value which may not authorize writing on the mounted directory. If you don't need to mount a directory then no problem with not passing `LOCAL_USER_ID`

**Comment by prudhomm** [comment]
ah you mean I forgot to update feelpp-toolboxes ? 
I will check :)

**Comment by gdolle** [comment]
@prudhomm in fact it seems the tag `develop-ubuntu-16.10` is an old tag (the image date from 4month) and kept in dockerhub (history for reproducibility). It should be ok with `develop` or `latest` (or `stable` for release).
